server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri: mongodb://root:991228@localhost:27017/?authSource=admin
      database: xc_media
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  upload‐location: D:/video/
  ffmpeg-path: D:/ffmpeg-20200413-59e3a9a-win64-static/bin/ffmpeg.exe